// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkWI_FpzKMm64cNG0jjmZlEs15GAq3wJk',
    appId: '1:835876113834:web:63e548db1f3a6de0106fd3',
    messagingSenderId: '835876113834',
    projectId: 'android-forum-project',
    authDomain: 'android-forum-project.firebaseapp.com',
    storageBucket: 'android-forum-project.appspot.com',
    measurementId: 'G-XYXP5GH2PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7cLbfrzQpyERvdhaQSrnN1x4ywG02p9U',
    appId: '1:835876113834:android:2f547a21b1ec5bd9106fd3',
    messagingSenderId: '835876113834',
    projectId: 'android-forum-project',
    storageBucket: 'android-forum-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4qSmjuE4jI9qTTFn7d0kRrbudVzdljgU',
    appId: '1:835876113834:ios:98813ac0108d6ce8106fd3',
    messagingSenderId: '835876113834',
    projectId: 'android-forum-project',
    storageBucket: 'android-forum-project.appspot.com',
    iosClientId: '835876113834-j8kccgl3i1sfh1702h9g295rhgoej9lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.forum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4qSmjuE4jI9qTTFn7d0kRrbudVzdljgU',
    appId: '1:835876113834:ios:60c8eb652c5e2272106fd3',
    messagingSenderId: '835876113834',
    projectId: 'android-forum-project',
    storageBucket: 'android-forum-project.appspot.com',
    iosClientId: '835876113834-bov3rd5h218lj6up95h3id5l0p8b86me.apps.googleusercontent.com',
    iosBundleId: 'com.example.forum.RunnerTests',
  );
}
